[package]
name = "blender_plugin"
version = "0.1.0"
authors = ["monax-owo"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { workspace = true }
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.9"
